Repository vapor/database-kit, pull requests merged in 2018-02, with the labels that each got.

#6 Fix nil assert in DatabaseConnection.connect(to:)
  Sources/DatabaseKit/Connection/DatabaseConnection.swift
Labels: bug

#8 foreign key actions
  Sources/SQL/Schema/SchemaForeignKey.swift
  Sources/SQL/Serialization/SQLSerializer+SchemaQuery.swift
  Sources/SQL/Serialization/SQLSerializer.swift
Labels: enhancement

#10 subcontainer fixes
  Sources/DatabaseKit/Service/Container+CachedConnection.swift
Labels: bug

#11 remove connection config
  Sources/DatabaseKit/Connection/DatabaseConnection.swift
  Sources/DatabaseKit/Connection/DatabaseConnectionPool.swift
  Sources/DatabaseKit/Database/Database.swift
  Sources/DatabaseKit/DatabaseKitError.swift
  Sources/DatabaseKit/Service/Container+CachedConnection.swift
  Sources/DatabaseKit/Service/Container+Connection.swift
  Sources/DatabaseKit/Service/DatabaseConnectionPoolCache.swift
  Sources/DatabaseKit/Service/DatabaseConnectionPoolConfig.swift
  Sources/DatabaseKit/Service/DatabaseKitProvider.swift
Labels: bug, enhancement

#12 sql cleanup
  .DS_Store
  Sources/SQL/Schema/SchemaQuery.swift
  Sources/SQL/Serialization/SQLSerializer+SchemaQuery.swift
Labels: enhancement

#3 database-kit beta
  .DS_Store
  LICENSE
  Package.swift
  README.md
  Sources/DatabaseKit/Connection/DatabaseConnection.swift
  Sources/DatabaseKit/Connection/DatabaseConnectionPool.swift
  Sources/DatabaseKit/Database/Database.swift
  Sources/DatabaseKit/DatabaseKitError.swift
  Sources/DatabaseKit/KeyedCache/KeyedCache.swift
  Sources/DatabaseKit/KeyedCache/MemoryKeyedCache.swift
  Sources/DatabaseKit/Service/Container+CachedConnection.swift
  Sources/DatabaseKit/Service/Container+Connection.swift
  Sources/DatabaseKit/Service/Container+ConnectionPool.swift
  Sources/DatabaseKit/Service/DatabaseConnectionPoolCache.swift
  Sources/DatabaseKit/Service/DatabaseConnectionPoolConfig.swift
  Sources/DatabaseKit/Service/DatabaseKitProvider.swift
  Sources/SQL/Data/DataJoin.swift
  Sources/SQL/Schema/SchemaForeignKey.swift
  Sources/SQL/Schema/SchemaQuery.swift
  Sources/SQL/Serialization/SQLSerializer+SchemaQuery.swift
  Sources/SQL/Serialization/SQLSerializer.swift
  circle.yml
Labels: enhancement
